Repository ethereum/ethereum-org-fork, pull requests merged in 2023-11, with the labels that each got.

#74 Implement PageMetadata component
  src/components/PageMetadata.tsx
  src/layouts/Roadmap.tsx
  src/layouts/Staking.tsx
  src/layouts/Upgrade.tsx
  src/layouts/UseCases.tsx
  src/pages/[...slug].tsx
  src/pages/_document.tsx
  src/pages/developers/tutorials/[...tutorial].tsx
  tsconfig.json
Labels: review needed :eyes:, content :fountain_pen:

#93 Add updatePublishDate.sh preversion script
  package.json
  src/data/published.json
  src/hooks/useClientSideGitHubContributors.ts
  src/lib/constants.ts
  src/lib/utils/gh.ts
  src/pages/[...slug].tsx
  src/pages/developers/tutorials/[...tutorial].tsx
  src/scripts/updatePublishDate.sh
Labels: review needed :eyes:, content :fountain_pen:, tooling :wrench:, dependencies :package:

#100 Move getLastDeployDate to dedicated util file
  src/lib/utils/getLastDeployDate.ts
  src/lib/utils/gh.ts
  src/pages/[...slug].tsx
  src/pages/developers/tutorials/[...tutorial].tsx
Labels: review needed :eyes:, content :fountain_pen:

#103 i18n: patch html lang
  src/pages/_document.tsx
Labels: review needed :eyes:, content :fountain_pen:

#101 Refactor generateTableOfContents
  src/components/TableOfContents/ItemsList.tsx
  src/components/TableOfContents/TableOfContentsLink.tsx
  src/components/TableOfContents/TableOfContentsMobile.tsx
  src/components/TableOfContents/index.tsx
  src/components/UpgradeTableOfContents.tsx
  src/lib/interfaces.ts
  src/lib/types.ts
  src/lib/utils/md.ts
  src/lib/utils/toc.ts
  src/pages/[...slug].tsx
Labels: review needed :eyes:, content :fountain_pen:

#60 Tutorials markdown layout
  .gitignore
  netlify.toml
  package.json
  public/content/developers/tutorials/waffle-dynamic-mocking-and-testing-calls/index.md
  public/content/translations/de/developers/tutorials/how-to-view-nft-in-metamask/index.md
  public/content/translations/de/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
  public/content/translations/es/developers/tutorials/how-to-view-nft-in-metamask/index.md
  public/content/translations/es/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
  public/content/translations/fr/developers/tutorials/waffle-dynamic-mocking-and-testing-calls/index.md
  public/content/translations/id/developers/tutorials/how-to-view-nft-in-metamask/index.md
  public/content/translations/id/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
  public/content/translations/id/developers/tutorials/waffle-dynamic-mocking-and-testing-calls/index.md
  public/content/translations/it/developers/tutorials/waffle-dynamic-mocking-and-testing-calls/index.md
  public/content/translations/ja/developers/tutorials/waffle-dynamic-mocking-and-testing-calls/index.md
  public/content/translations/pl/developers/tutorials/deploying-your-first-smart-contract/index.md
  public/content/translations/pl/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md
  public/content/translations/pl/developers/tutorials/how-to-use-slither-to-find-smart-contract-bugs/index.md
  public/content/translations/pl/developers/tutorials/interact-with-other-contracts-from-solidity/index.md
  public/content/translations/pl/developers/tutorials/logging-events-smart-contracts/index.md
  public/content/translations/pl/developers/tutorials/run-node-raspberry-pi/index.md
  public/content/translations/pl/developers/tutorials/the-graph-fixing-web3-data-querying/index.md
  public/content/translations/pl/developers/tutorials/transfers-and-approval-of-erc-20-tokens-from-a-solidity-smart-contract/index.md
  public/content/translations/pl/developers/tutorials/using-websockets/index.md
  public/content/translations/pl/developers/tutorials/waffle-dynamic-mocking-and-testing-calls/index.md
  public/content/translations/ro/developers/tutorials/how-to-view-nft-in-metamask/index.md
  public/content/translations/ro/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
  public/content/translations/ro/developers/tutorials/waffle-dynamic-mocking-and-testing-calls/index.md
  public/content/translations/tr/developers/tutorials/how-to-view-nft-in-metamask/index.md
  public/content/translations/tr/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
  public/content/translations/zh/developers/tutorials/waffle-dynamic-mocking-and-testing-calls/index.md
  src/components/Banners/PostMergeBanner.tsx
  src/components/Codeblock.tsx
  src/components/FeedbackCard.tsx
  src/components/TutorialMetadata.tsx
  src/layouts/RootLayout.tsx
  src/layouts/Tutorial.tsx
  src/lib/constants.ts
  src/lib/interfaces.ts
  src/lib/utils/date.ts
  src/lib/utils/md.ts
  src/pages/[...slug].tsx
  src/pages/developers/tutorials/[...tutorial].tsx
  tsconfig.json
  yarn.lock
Labels: review needed :eyes:, content :fountain_pen:, tooling :wrench:, dependencies :package:

#82 Migrate components and enable paths for Static layout
  public/content/translations/hu/developers/docs/blocks/index.md
  public/content/translations/hu/developers/docs/evm/index.md
  public/content/translations/hu/developers/docs/gas/index.md
  public/content/translations/hu/developers/docs/nodes-and-clients/index.md
  public/content/translations/hu/developers/docs/transactions/index.md
  public/content/translations/id/contributing/translation-program/index.md
  public/content/translations/pl/developers/docs/accounts/index.md
  public/content/translations/pl/developers/docs/blocks/index.md
  public/content/translations/pl/developers/docs/evm/index.md
  public/content/translations/pl/developers/docs/gas/index.md
  public/content/translations/pl/developers/docs/nodes-and-clients/index.md
  public/content/translations/pl/developers/docs/scaling/layer-2-rollups/index.md
  public/content/translations/pl/developers/docs/transactions/index.md
  public/content/translations/ro/developers/docs/layer-2-scaling/index.md
  public/content/translations/sl/contributing/translation-program/faq/index.md
  public/content/translations/sl/contributing/translation-program/index.md
  public/content/translations/tr/contributing/translation-program/index.md
  src/components/Contributors.tsx
  src/components/Logo.tsx
  src/components/MatomoOptOut.tsx
  src/components/MdComponents.tsx
  src/components/SocialListItem.tsx
  src/components/TranslationChartImage.tsx
  src/layouts/Staking.tsx
  src/layouts/Static.tsx
  src/lib/utils/md.ts
  tsconfig.json
Labels: review needed :eyes:

#107 Add react-select package
  package.json
  src/components/Staking/StakingLaunchpadWidget.tsx
  tsconfig.json
  yarn.lock
Labels: review needed :eyes:, dependencies :package:

#98 fix(md.ts): handle Windows file paths for `getPostSlugs`
  src/lib/utils/md.ts
Labels: review needed :eyes:

#109 fix: external pdf links
  src/components/Link.tsx
  src/lib/utils/url.ts
Labels: review needed :eyes:

#85 Build flags to improve DX
  .env.example
  README.md
  next.config.js
  src/lib/constants.ts
Labels: review needed :eyes:, documentation :book:

#105 fix: color mode
  src/@chakra-ui/styles.ts
  src/@chakra-ui/theme.ts
  src/pages/_document.tsx
Labels: review needed :eyes:, content :fountain_pen:

#108 Update GitHub contributors usage
  src/components/FileContributors.tsx
  src/components/GitHubContributors.tsx
  src/layouts/Static.tsx
  src/layouts/Tutorial.tsx
Labels: review needed :eyes:

#104 Fix unicode parsing logic for toc items
  src/lib/utils/toc.ts
Labels: review needed :eyes:

#118 Fix translations not loading in some pages
  src/components/EnergyConsumptionChart.tsx
  src/components/Translation.tsx
  src/lib/utils/translations.ts
  src/pages/[...slug].tsx
Labels: review needed :eyes:, content :fountain_pen:

#99 fix(MarkdownImage): resolve src path slashes produced in Windows OS
  src/components/MarkdownImage.tsx
  src/lib/rehype/rehypeImg.ts
Labels: review needed :eyes:

#114 Developer docs markdown layout
  next.config.js
  package.json
  public/content/translations/fa/developers/docs/nodes-and-clients/index.md
  public/content/translations/hu/developers/docs/nodes-and-clients/index.md
  public/content/translations/id/developers/docs/nodes-and-clients/index.md
  public/content/translations/pl/developers/docs/nodes-and-clients/index.md
  public/content/translations/ro/developers/docs/nodes-and-clients/index.md
  public/content/translations/ru/developers/docs/nodes-and-clients/index.md
  src/components/CallToContribute.tsx
  src/components/Codeblock.tsx
  src/components/DeveloperDocsLinks.tsx
  src/components/DocsNav.tsx
  src/components/RollupProductDevDoc.tsx
  src/components/SideNav.tsx
  src/components/SideNavMobile.tsx
  src/hooks/useActiveHash.ts
  src/layouts/Docs.tsx
  src/lib/interfaces.ts
  src/lib/utils/md.ts
  src/lib/utils/translations.ts
  src/pages/[...slug].tsx
  tsconfig.json
  yarn.lock
Labels: review needed :eyes:, content :fountain_pen:, dependencies :package:

#123 feat(utils): create a `toPosixPath` method
  src/components/MarkdownImage.tsx
  src/layouts/RootLayout.tsx
  src/lib/utils/md.ts
  src/lib/utils/relativePath.ts
Labels: review needed :eyes:

#133 Moves RootLayout to _app
  src/lib/interfaces.ts
  src/pages/[...slug].tsx
  src/pages/_app.tsx
Labels: review needed :eyes:, content :fountain_pen:

#135 Remove warning for missing page title ids
  src/components/SideNavMobile.tsx
Labels: review needed :eyes:

#129 refactor([...slug]): update type constraints
  src/layouts/Docs.tsx
  src/layouts/Roadmap.tsx
  src/layouts/Staking.tsx
  src/layouts/Static.tsx
  src/layouts/Tutorial.tsx
  src/layouts/Upgrade.tsx
  src/layouts/UseCases.tsx
  src/lib/types.ts
  src/pages/[...slug].tsx
Labels: review needed :eyes:, content :fountain_pen:

#149 Refactor out temporalAllowedPages in md.ts
  .env.example
  src/lib/utils/md.ts
Labels: review needed :eyes:

#151 Revert "Refactor out temporalAllowedPages in md.ts"
  .env.example
  src/lib/utils/md.ts
Labels: review needed :eyes:

#137 Add `Layout` type
  src/lib/interfaces.ts
  src/lib/types.ts
  src/pages/[...slug].tsx
Labels: review needed :eyes:, content :fountain_pen:

#140 Fix hero images
  src/components/Image.tsx
  src/layouts/Roadmap.tsx
  src/layouts/Staking.tsx
  src/layouts/Upgrade.tsx
  src/layouts/UseCases.tsx
Labels: review needed :eyes:

#141 Not found page
  src/pages/404.tsx
Labels: review needed :eyes:, content :fountain_pen:

#142 Require namespaces logic refactor
  src/components/Translation.tsx
  src/lib/utils/translations.ts
  src/pages/404.tsx
  src/pages/[...slug].tsx
Labels: review needed :eyes:, content :fountain_pen:

#124 implement CrowdinContributors component
  src/components/CrowdinContributors.tsx
  src/components/FileContributors.tsx
  src/components/FileContributorsCrowdin.tsx
  src/components/GitHubContributors.tsx
  src/hooks/useClientSideGitHubContributors.ts
  src/hooks/useClientSideGitHubLastEdit.ts
  src/layouts/Docs.tsx
  src/layouts/Tutorial.tsx
  src/lib/interfaces.ts
  src/lib/types.ts
  src/lib/utils/crowdin.ts
  src/lib/utils/md.ts
  src/pages/[...slug].tsx
Labels: review needed :eyes:, content :fountain_pen:

#139 Implement Assets page
  public/assets/svgs/eth-diamond-black-gray.svg
  public/assets/svgs/eth-diamond-black-white.svg
  public/assets/svgs/eth-diamond-black.svg
  public/assets/svgs/eth-diamond-glyph.svg
  public/assets/svgs/eth-diamond-purple-purple.svg
  public/assets/svgs/eth-diamond-purple-white.svg
  public/assets/svgs/eth-diamond-purple.svg
  public/assets/svgs/eth-diamond-rainbow.svg
  public/assets/svgs/eth-glyph-colored.svg
  public/assets/svgs/ethereum-logo-landscape-black-gray.svg
  public/assets/svgs/ethereum-logo-landscape-black.svg
  public/assets/svgs/ethereum-logo-landscape-purple-purple.svg
  public/assets/svgs/ethereum-logo-landscape-purple-white.svg
  public/assets/svgs/ethereum-logo-landscape-purple.svg
  public/assets/svgs/ethereum-logo-portrait-black-gray.svg
  public/assets/svgs/ethereum-logo-portrait-black.svg
  public/assets/svgs/ethereum-logo-portrait-purple-purple.svg
  public/assets/svgs/ethereum-logo-portrait-purple.svg
  public/assets/svgs/ethereum-wordmark-black-gray.svg
  public/assets/svgs/ethereum-wordmark-black.svg
  public/assets/svgs/ethereum-wordmark-purple-purple.svg
  public/assets/svgs/ethereum-wordmark-purple-white.svg
  public/assets/svgs/ethereum-wordmark-purple.svg
  public/assets/svgs/merge-panda.svg
  src/components/AssetDownload/AssetDownloadArtist.tsx
  src/components/AssetDownload/AssetDownloadImage.tsx
  src/components/AssetDownload/index.tsx
  src/lib/utils/translations.ts
  src/pages/assets.tsx
  tsconfig.json
Labels: review needed :eyes:, content :fountain_pen:

#144 Implement Bug Bounty page
  .github/CODEOWNERS
  src/components/Breadcrumbs/Breadcrumbs.stories.tsx
  src/components/Breadcrumbs/index.tsx
  src/components/BugBountyCards.tsx
  src/components/CardList.tsx
  src/components/Leaderboard.tsx
  src/data/consensus-bounty-hunters.csv
  src/data/consensus-bounty-hunters.json
  src/data/execution-bounty-hunters.csv
  src/data/execution-bounty-hunters.json
  src/intl/ar/page-bug-bounty.json
  src/intl/en/common.json
  src/intl/en/page-bug-bounty.json
  src/intl/hi/page-bug-bounty.json
  src/lib/constants.ts
  src/lib/utils/resizeImage.ts
  src/lib/utils/translations.ts
  src/pages/bug-bounty.tsx
  tsconfig.json
Labels: review needed :eyes:, content :fountain_pen:, tooling :wrench:
