Repository ethereum/ethereum-org-fork, pull requests merged in 2023-10, with the labels that each got.

#36 Update Chakra theme styles
  src/@chakra-ui/components/components.utils.ts
  src/@chakra-ui/foundations/typography.ts
  src/@chakra-ui/styles.ts
  src/@chakra-ui/theme.ts
Labels: review needed :eyes:

#39 Netlify ignore files
  .gitignore
  netlify.toml
  package.json
  yarn.lock
Labels: review needed :eyes:, content :fountain_pen:, tooling :wrench:, dependencies :package:

#33 UseCases layout with associated components
  .gitignore
  netlify.toml
  package.json
  public/content/dao/index.md
  public/content/decentralized-identity/index.md
  public/content/defi/index.md
  public/content/desci/index.md
  public/content/nft/index.md
  public/content/refi/index.md
  public/content/refi/refi-regenerative-economy-diagram.png
  public/content/social-networks/index.md
  src/components/ButtonDropdown.tsx
  src/components/Footer.tsx
  src/components/Glossary/GlossaryDefinition/index.tsx
  src/components/Glossary/GlossaryTooltip/index.tsx
  src/components/Quiz/QuizRadioGroup.tsx
  src/components/Quiz/QuizSummary.tsx
  src/components/Quiz/QuizWidget.tsx
  src/components/Quiz/context.ts
  src/components/Quiz/utils.ts
  src/components/RandomAppList.tsx
  src/components/TableOfContents/ItemsList.tsx
  src/components/TableOfContents/TableOfContentsLink.tsx
  src/components/TableOfContents/TableOfContentsMobile.tsx
  src/components/TableOfContents/index.tsx
  src/components/TableOfContents/utils.ts
  src/components/Tooltip.tsx
  src/components/UpgradeStatus.tsx
  src/components/UpgradeTableOfContents.tsx
  src/data/quizzes/index.ts
  src/data/quizzes/questionBank.ts
  src/hooks/useActiveHash.ts
  src/layouts/Static.tsx
  src/layouts/UseCases.tsx
  src/layouts/index.ts
  src/lib/constants.ts
  src/lib/interfaces.ts
  src/lib/rehype/rehypeHeadingIds.ts
  src/lib/types.ts
  src/lib/utils/getSummaryPoints.ts
  src/lib/utils/isMobile.ts
  src/lib/utils/matomo.ts
  src/lib/utils/md.ts
  src/lib/utils/numberToPercent.ts
  src/lib/utils/toc.ts
  src/lib/utils/translations.ts
  src/pages/[...slug].tsx
  tsconfig.json
  yarn.lock
Labels: review needed :eyes:, content :fountain_pen:, tooling :wrench:, dependencies :package:

#50 Fix font
  src/@chakra-ui/foundations/typography.ts
Labels: review needed :eyes:

#51 fix: `getLastModifiedDate`
  src/lib/constants.ts
  src/lib/utils/gh.ts
Labels: review needed :eyes:

#52 Fix static styles
  src/layouts/Static.tsx
Labels: review needed :eyes:

#53 fix: /energy-consumption style tags
  public/content/translations/ca/energy-consumption/index.md
  public/content/translations/fa/energy-consumption/index.md
  public/content/translations/id/energy-consumption/index.md
  public/content/translations/nl/energy-consumption/index.md
  public/content/translations/ro/energy-consumption/index.md
  public/content/translations/uk/energy-consumption/index.md
  src/lib/utils/md.ts
Labels: review needed :eyes:

#38 Implement Roadmap and Upgrade layouts
  public/content/roadmap/index.md
  public/content/roadmap/scaling/index.md
  public/content/translations/de/roadmap/index.md
  public/content/translations/de/roadmap/scaling/index.md
  public/content/translations/it/roadmap/index.md
  public/content/translations/it/roadmap/scaling/index.md
  public/content/translations/tr/roadmap/index.md
  public/content/translations/tr/roadmap/scaling/index.md
  public/content/translations/zh-tw/roadmap/index.md
  public/content/translations/zh-tw/roadmap/scaling/index.md
  public/content/translations/zh/roadmap/index.md
  public/content/translations/zh/roadmap/scaling/index.md
  public/upgrades/merge-infographic-bg.svg
  src/components/BeaconChainActions.tsx
  src/components/Card/Card.stories.tsx
  src/components/Card/index.tsx
  src/components/CardList.tsx
  src/components/MergeArticleList.tsx
  src/components/MergeInfographic/Background.tsx
  src/components/MergeInfographic/index.tsx
  src/components/Roadmap/RoadmapActionCard.tsx
  src/components/Roadmap/RoadmapImageContent.tsx
  src/components/SectionNav.tsx
  src/components/ShardChainsList.tsx
  src/components/UpgradeStatus.tsx
  src/layouts/Roadmap.tsx
  src/layouts/Upgrade.tsx
  src/layouts/UseCases.tsx
  src/layouts/index.ts
  src/lib/interfaces.ts
  src/lib/types.ts
  src/lib/utils/md.ts
  src/pages/[...slug].tsx
  tsconfig.json
Labels: review needed :eyes:, content :fountain_pen:, tooling :wrench:, dependencies :package:

#54 i18n: Link & Breadcrumbs
  src/components/Breadcrumbs/index.tsx
  src/components/Link.tsx
  src/layouts/Roadmap.tsx
Labels: review needed :eyes:

#55 i18n: TranslationBanner & TranslationBannerLegal
  src/components/Footer.tsx
  src/components/TranslationBanner.tsx
  src/layouts/RootLayout.tsx
  src/lib/interfaces.ts
  src/lib/utils/md.ts
  src/pages/[...slug].tsx
  src/pages/developers/tutorials/[...tutorial].tsx
  tsconfig.json
Labels: review needed :eyes:, content :fountain_pen:

#44 Table of contents
  src/components/TableOfContents/ItemsList.tsx
  src/components/TableOfContents/TableOfContentsLink.tsx
  src/components/TableOfContents/index.tsx
  src/components/UpgradeTableOfContents.tsx
  src/layouts/Static.tsx
  src/lib/rehype/rehypeHeadingIds.ts
  src/lib/utils/toc.ts
Labels: review needed :eyes:

#57 Migrate and implement scrollIntoView util
  src/components/Buttons/Button.tsx
  src/lib/utils/scrollIntoView.ts
Labels: review needed :eyes:

#61 Bump Nextjs version
  package.json
  yarn.lock
Labels: dependencies :package:

#64 feat: Last deploy date
  src/components/Footer.tsx
  src/layouts/RootLayout.tsx
  src/lib/constants.ts
  src/lib/interfaces.ts
  src/lib/utils/gh.ts
  src/pages/[...slug].tsx
  src/pages/developers/tutorials/[...tutorial].tsx
Labels: review needed :eyes:, content :fountain_pen:

#45 Shared markdown components
  src/components/MdComponents.tsx
  src/layouts/Roadmap.tsx
  src/layouts/Staking.tsx
  src/layouts/Static.tsx
  src/layouts/Upgrade.tsx
  src/layouts/UseCases.tsx
  src/pages/[...slug].tsx
Labels: review needed :eyes:, content :fountain_pen:, dependencies :package:

#67 Revert to OldHeading on Static
  src/layouts/Static.tsx
Labels: review needed :eyes:

#68 Catch empty deploys with fallback value
  src/lib/utils/gh.ts
Labels: review needed :eyes:

#71 Autolink images
  src/components/MarkdownImage.tsx
Labels: review needed :eyes:

#49 Autolink headers
  src/components/MdComponents.tsx
  src/layouts/Staking.tsx
  src/layouts/Static.tsx
  src/lib/rehype/rehypeHeadingIds.ts
Labels: review needed :eyes:, content :fountain_pen:, dependencies :package:

#65 Make alt field required for Upgrade layout
  public/content/roadmap/beacon-chain/index.md
  public/content/roadmap/merge/index.md
  public/content/translations/ar/roadmap/beacon-chain/index.md
  public/content/translations/ar/roadmap/merge/index.md
  public/content/translations/bg/roadmap/beacon-chain/index.md
  public/content/translations/bg/roadmap/merge/index.md
  public/content/translations/ca/roadmap/beacon-chain/index.md
  public/content/translations/ca/roadmap/merge/index.md
  public/content/translations/de/roadmap/beacon-chain/index.md
  public/content/translations/de/roadmap/merge/index.md
  public/content/translations/el/roadmap/beacon-chain/index.md
  public/content/translations/el/roadmap/merge/index.md
  public/content/translations/es/roadmap/beacon-chain/index.md
  public/content/translations/es/roadmap/merge/index.md
  public/content/translations/fa/roadmap/beacon-chain/index.md
  public/content/translations/fa/roadmap/merge/index.md
  public/content/translations/fr/roadmap/beacon-chain/index.md
  public/content/translations/fr/roadmap/merge/index.md
  public/content/translations/hi/roadmap/beacon-chain/index.md
  public/content/translations/hi/roadmap/merge/index.md
  public/content/translations/hr/roadmap/beacon-chain/index.md
  public/content/translations/hr/roadmap/merge/index.md
  public/content/translations/hu/roadmap/beacon-chain/index.md
  public/content/translations/hu/roadmap/merge/index.md
  public/content/translations/id/roadmap/beacon-chain/index.md
  public/content/translations/id/roadmap/merge/index.md
  public/content/translations/it/roadmap/beacon-chain/index.md
  public/content/translations/it/roadmap/merge/index.md
  public/content/translations/ja/roadmap/beacon-chain/index.md
  public/content/translations/ja/roadmap/merge/index.md
  public/content/translations/ml/roadmap/beacon-chain/index.md
  public/content/translations/ml/roadmap/merge/index.md
  public/content/translations/nl/roadmap/beacon-chain/index.md
  public/content/translations/nl/roadmap/merge/index.md
  public/content/translations/pl/roadmap/beacon-chain/index.md
  public/content/translations/pl/roadmap/merge/index.md
  public/content/translations/pt-br/roadmap/beacon-chain/index.md
  public/content/translations/pt-br/roadmap/merge/index.md
  public/content/translations/ro/roadmap/beacon-chain/index.md
  public/content/translations/ro/roadmap/merge/index.md
  public/content/translations/ru/roadmap/beacon-chain/index.md
  public/content/translations/ru/roadmap/merge/index.md
  public/content/translations/sl/roadmap/beacon-chain/index.md
  public/content/translations/sl/roadmap/merge/index.md
  public/content/translations/sw/roadmap/beacon-chain/index.md
  public/content/translations/sw/roadmap/merge/index.md
  public/content/translations/tr/roadmap/beacon-chain/index.md
  public/content/translations/tr/roadmap/merge/index.md
  public/content/translations/uk/roadmap/beacon-chain/index.md
  public/content/translations/uk/roadmap/merge/index.md
  public/content/translations/zh-tw/roadmap/beacon-chain/index.md
  public/content/translations/zh-tw/roadmap/merge/index.md
  public/content/translations/zh/roadmap/beacon-chain/index.md
  public/content/translations/zh/roadmap/merge/index.md
  src/layouts/Upgrade.tsx
  src/lib/interfaces.ts
Labels: review needed :eyes:

#58 Implement MeetupList component
  src/components/MeetupList.tsx
  src/layouts/Static.tsx
Labels: review needed :eyes:

#77 Use useRouter locale; remove hardcoded language
  src/components/History/NetworkUpgradeSummary.tsx
  src/components/Quiz/QuizSummary.tsx
  src/layouts/Static.tsx
  src/layouts/Upgrade.tsx
Labels: review needed :eyes:

#83 Static layout paths
  public/content/contributing/translation-program/translatathon/index.md
  public/content/translations/id/contributing/translation-program/how-to-translate/index.md
  public/content/translations/sl/contributing/translation-program/how-to-translate/index.md
  public/content/translations/tr/contributing/translation-program/how-to-translate/index.md
  src/components/Contributors.tsx
  src/components/SocialListItem.tsx
  src/lib/utils/md.ts
Labels: review needed :eyes:, content :fountain_pen:

#80 Deprecate Event layout
  public/content/contributing/translation-program/translatathon/index.md
  src/layouts/Event.tsx
  src/layouts/index.ts
  src/pages/[...slug].tsx
Labels: review needed :eyes:, content :fountain_pen:

#84 fix: replace hardcoded value with DEFAULT_LOCALE constant
  src/components/History/NetworkUpgradeSummary.tsx
Labels: review needed :eyes:

#81 Patch ToC logic
  src/components/TableOfContents/index.tsx
  src/lib/utils/toc.ts
Labels: review needed :eyes:

#75 Add "Edit page" button to desktop ToC
  src/layouts/Static.tsx
Labels: review needed :eyes:

#66 Implement GitHubContributors
  .env.example
  src/components/FileContributors.tsx
  src/components/FileContributorsCrowdin.tsx
  src/components/FileContributorsGitHub.tsx
  src/components/GitHubContributors.tsx
  src/hooks/useClientSideGitHubContributors.ts
  src/layouts/Static.tsx
  src/lib/constants.ts
  src/lib/interfaces.ts
  src/lib/types.ts
  src/lib/utils/gh.ts
  src/pages/[...slug].tsx
  src/pages/developers/tutorials/[...tutorial].tsx
  tsconfig.json
Labels: review needed :eyes:, content :fountain_pen:

#73 Migrate Crowdin scripts
  package.json
  src/lib/constants.ts
  src/lib/types.ts
  src/scripts/crowdin/api-client/crowdinClient.ts
  src/scripts/crowdin/getCrowdinContributors.ts
  src/scripts/crowdin/reports/dataHelpers.ts
  src/scripts/crowdin/reports/fileHelpers.ts
  src/scripts/crowdin/reports/getTranslationCostsReports.ts
  src/scripts/crowdin/reports/reportsHelpers.ts
  src/scripts/crowdin/source-files/fetchAndSaveDirectories.ts
  src/scripts/crowdin/source-files/fetchAndSaveFileIds.ts
  src/scripts/crowdin/utils.ts
  src/scripts/markdownChecker.ts
  yarn.lock
Labels: review needed :eyes:, tooling :wrench:, dependencies :package:

#92 Upgrade Next to v14
  package.json
  yarn.lock
Labels: dependencies :package:
