Repository ethereum/ethereum-org-fork, pull requests merged in 2023-12, with the labels that each got.

#106 feat: initialize setup of Storybook
  .eslintrc.json
  .storybook/i18next.ts
  .storybook/main.ts
  .storybook/manager.ts
  .storybook/preview-logo.svg
  .storybook/preview.ts
  .storybook/theme.ts
  package.json
  src/components/Buttons/Button.stories.tsx
  src/lib/rehype/remarkInferToc.ts
  yarn.lock
Labels: review needed :eyes:, dependencies :package:

#126 Developer home page
  src/components/Hero/CallToAction.tsx
  src/components/Hero/HubHero/index.tsx
  src/components/Hero/utils.ts
  src/pages/developers/index.tsx
Labels: review needed :eyes:

#150 feat: Languages page
  src/lib/types.ts
  src/lib/utils/translations.ts
  src/pages/languages.tsx
Labels: review needed :eyes:, content :fountain_pen:

#161 Feedback widget
  package.json
  src/components/FeedbackCard.tsx
  src/components/FeedbackWidget.tsx
  src/hooks/useKeyPress.ts
  src/hooks/useOnClickOutside.ts
  src/hooks/useSurvey.ts
  src/layouts/RootLayout.tsx
  tsconfig.json
  yarn.lock
Labels: review needed :eyes:, dependencies :package:

#147 Home page
  package.json
  src/components/ActionCard.tsx
  src/components/Breadcrumbs/index.tsx
  src/components/Codeblock.tsx
  src/components/CommunityEvents/index.tsx
  src/components/CommunityEvents/useCommunityEvents.ts
  src/components/Hero/ContentHero/index.tsx
  src/components/Hero/HomeHero/index.tsx
  src/components/Hero/utils.ts
  src/components/Staking/StakingCommunityCallout.tsx
  src/components/TitleCardList.tsx
  src/components/Translation.tsx
  src/lib/api/calendarEvents.ts
  src/lib/constants.ts
  src/lib/interfaces.ts
  src/lib/utils/runOnlyOnce.ts
  src/lib/utils/translations.ts
  src/lib/utils/url.ts
  src/pages/index.tsx
  tsconfig.json
  yarn.lock
Labels: review needed :eyes:, content :fountain_pen:, dependencies :package:

#146 Implement Run A Node page
  next.config.js
  package.json
  src/components/Breadcrumbs/index.tsx
  src/components/ExpandableCard.tsx
  src/components/ExpandableInfo.tsx
  src/components/GatsbyImage.tsx
  src/components/Hero/CallToAction.tsx
  src/components/Hero/ContentHero/ContentHero.stories.tsx
  src/components/Hero/ContentHero/index.tsx
  src/components/Hero/HomeHero/HomeHero.stories.tsx
  src/components/Hero/HomeHero/index.tsx
  src/components/Hero/HubHero/HubHero.stories.tsx
  src/components/Hero/HubHero/index.tsx
  src/components/Hero/MdxHero/MdxHero.stories.tsx
  src/components/Hero/MdxHero/index.tsx
  src/components/Hero/index.ts
  src/components/Hero/utils.ts
  src/components/Morpher.tsx
  src/components/PageHero.tsx
  src/components/icons/run-a-node/DecentralizationEthGlyphIcon.tsx
  src/components/icons/run-a-node/DecentralizationGlyphIcon.tsx
  src/components/icons/run-a-node/DownloadGlyphIcon.tsx
  src/components/icons/run-a-node/EarthGlyphIcon.tsx
  src/components/icons/run-a-node/HardwareGlyphIcon.tsx
  src/components/icons/run-a-node/MegaphoneGlyphIcon.tsx
  src/components/icons/run-a-node/PrivacyGlyphIcon.tsx
  src/components/icons/run-a-node/SovereigntyGlyphIcon.tsx
  src/components/icons/run-a-node/VoteGlyphIcon.tsx
  src/components/icons/run-a-node/index.ts
  src/layouts/Staking.tsx
  src/lib/interfaces.ts
  src/lib/types.ts
  src/lib/utils/translations.ts
  src/pages/run-a-node.tsx
  tsconfig.json
  yarn.lock
Labels: review needed :eyes:, content :fountain_pen:, dependencies :package:

#165 Home page - remove revalidate option
  src/pages/index.tsx
Labels: review needed :eyes:, content :fountain_pen:

#167 Roadmap HubHero
  src/components/Hero/HubHero/index.tsx
  src/layouts/Roadmap.tsx
Labels: review needed :eyes:

#170 Add favicon
  public/favicon.ico
  src/components/PageMetadata.tsx
  src/pages/_document.tsx
Labels: review needed :eyes:, content :fountain_pen:

#172 Implement `unoptimized` for animated images
  src/components/MarkdownImage.tsx
Labels: review needed :eyes:

#159 /developers/tutorials page migration
  src/lib/utils/md.ts
  src/lib/utils/translations.ts
  src/lib/utils/tutorial.ts
  src/pages/developers/tutorials.tsx
Labels: review needed :eyes:

#152 Implement Get ETH page
  src/components/BeaconChainActions.tsx
  src/components/Buttons/Button.tsx
  src/components/Buttons/ButtonLink.tsx
  src/components/Buttons/ButtonTwoLines/ButtonTwoLines.stories.tsx
  src/components/Buttons/ButtonTwoLines/index.tsx
  src/components/Buttons/IconButton.tsx
  src/components/Buttons/index.ts
  src/components/CalloutBanner.tsx
  src/components/CardList.tsx
  src/components/CentralizedExchanges/index.tsx
  src/components/Emoji.tsx
  src/components/EthExchanges/use-eth-exchanges.ts
  src/components/EthPriceCard.tsx
  src/components/Hero/CallToAction.tsx
  src/components/InfoBanner.tsx
  src/components/Link.tsx
  src/components/MergeArticleList.tsx
  src/components/OldHeading.tsx
  src/components/OldText.tsx
  src/components/PageHero.tsx
  src/components/Staking/StakingGuides.tsx
  src/components/Translation.tsx
  src/data/exchanges-by-country.csv
  src/data/exchangesByCountry.ts
  src/hooks/useCentralizedExchanges.ts
  src/lib/constants.ts
  src/lib/utils/gh.ts
  src/lib/utils/resizeImage.ts
  src/lib/utils/scrollIntoView.ts
  src/lib/utils/translations.ts
  src/pages/[...slug].tsx
  src/pages/bug-bounty.tsx
  src/pages/get-eth.tsx
  tsconfig.json
Labels: review needed :eyes:, content :fountain_pen:

#171 Update .github/labeler.yml config file
  .github/labeler.yml
Labels: tooling :wrench:

#168 feat: Gas page
  src/components/PageHero.tsx
  src/lib/utils/translations.ts
  src/pages/gas.tsx
Labels: review needed :eyes:, content :fountain_pen:, translation :earth_africa:

#177 Add vision page, update associated components
  src/components/PageHero.tsx
  src/components/Trilemma/index.tsx
  src/components/Trilemma/useTrilemma.tsx
  src/lib/utils/translations.ts
  src/pages/roadmap/vision.tsx
  tsconfig.json
Labels: review needed :eyes:, internal :house:, translation :earth_africa:

#166 feat: Community page
  src/components/Hero/ContentHero/ContentHero.stories.tsx
  src/components/Hero/ContentHero/index.tsx
  src/components/Hero/HomeHero/HomeHero.stories.tsx
  src/components/Hero/HomeHero/index.tsx
  src/components/Hero/HubHero/HubHero.stories.tsx
  src/components/Hero/HubHero/index.tsx
  src/components/Hero/MdxHero/index.tsx
  src/layouts/Roadmap.tsx
  src/lib/interfaces.ts
  src/lib/types.ts
  src/pages/community.tsx
  src/pages/developers/index.tsx
  src/pages/index.tsx
  src/pages/quizzes.tsx
  tsconfig.json
Labels: review needed :eyes:, internal :house:, content :fountain_pen:, tooling :wrench:

#175 Add Learn page
  src/lib/utils/translations.ts
  src/pages/learn.tsx
Labels: review needed :eyes:, content :fountain_pen:, translation :earth_africa:

#184 [hot fix] Prop name patch
  src/pages/learn.tsx
Labels: review needed :eyes:, content :fountain_pen:

#179 Fix Nav TODO comments
  src/components/Nav/Dropdown.tsx
  src/components/Nav/index.tsx
  src/components/Nav/useNav.ts
Labels: review needed :eyes:

#164 Add custom redirects
  next.config.js
  public/_redirects
Labels: review needed :eyes:, internal :house:

#183 Add /web3 to learn-quizzes list
  src/lib/utils/translations.ts
Labels: review needed :eyes:, translation :earth_africa:

#174 Add Staking pages
  package.json
  src/components/LeftNavBar/index.tsx
  src/components/Staking/StakingHierarchy.tsx
  src/components/Staking/StakingStatsBox.tsx
  src/components/UpgradeTableOfContents.tsx
  src/hooks/useStakingConsiderations.ts
  src/lib/types.ts
  src/lib/utils/translations.ts
  src/pages/staking/deposit-contract.tsx
  src/pages/staking/index.tsx
  tsconfig.json
  yarn.lock
Labels: review needed :eyes:, internal :house:, tooling :wrench:, dependencies :package:, translation :earth_africa:

#176 migrate /wallets page
  src/components/Callout.tsx
  src/components/Simulator/NotificationPopover.tsx
  src/components/Simulator/WalletHome/AddressPill.tsx
  src/components/Simulator/WalletHome/NFTList.tsx
  src/components/Simulator/WalletHome/hooks/useNFT.tsx
  src/components/Simulator/WalletHome/interfaces.ts
  src/components/Simulator/index.tsx
  src/components/Simulator/screens/ConnectWeb3/index.tsx
  src/components/Simulator/screens/CreateAccount/WordSelectorButtons.tsx
  src/components/Simulator/screens/CreateAccount/index.tsx
  src/components/Simulator/screens/SendReceive/ReceiveEther.tsx
  src/components/Simulator/utils.ts
  src/data/WalletSimulatorData.tsx
  src/hooks/useEthPrice.tsx
  src/lib/utils/translations.ts
  src/pages/wallets/index.tsx
Labels: review needed :eyes:, tooling :wrench:, translation :earth_africa:

#185 Patch manifest and favicon
  public/manifest.json
  src/pages/_document.tsx
Labels: review needed :eyes:, content :fountain_pen:

#186 Patch PageHero mobile image positioning
  src/components/PageHero.tsx
Labels: review needed :eyes:

#188 Add redirect for /studio
  public/_redirects
Labels: review needed :eyes:

#180 Add "What is ETH" page
  next.config.js
  package.json
  src/components/ActionCard.tsx
  src/components/EthVideo.tsx
  src/lib/utils/translations.ts
  src/pages/eth.tsx
  yarn.lock
Labels: review needed :eyes:, internal :house:, content :fountain_pen:, dependencies :package:, translation :earth_africa:

#178 migrate /wallets/find-wallet page
  package.json
  public/wallets/xdefi.png
  src/components/Breadcrumbs/index.tsx
  src/components/FindWallet/WalletFilterSidebar/WalletFilterFeature/index.tsx
  src/components/FindWallet/WalletFilterSidebar/WalletFilterProfile/index.tsx
  src/components/FindWallet/WalletFilterSidebar/index.tsx
  src/components/FindWallet/WalletTable/index.tsx
  src/components/FindWallet/WalletTable/useWalletTable.tsx
  src/components/icons/staking/GreenCheckProductGlyphIcon.tsx
  src/data/wallets/wallet-data.ts
  src/data/wallets/wallet-filters.ts
  src/lib/constants.ts
  src/lib/utils/translations.ts
  src/pages/wallets/find-wallet.tsx
  yarn.lock
Labels: review needed :eyes:, tooling :wrench:, dependencies :package:, translation :earth_africa:

#195 Add key to UseCases hero, remount on path change
  src/layouts/UseCases.tsx
Labels: review needed :eyes:

#196 Fix redirect user to last page on locale change
  src/components/Nav/useNav.ts
  src/lib/constants.ts
  src/pages/languages.tsx
Labels: review needed :eyes:, content :fountain_pen:, tooling :wrench:

#197 Update GitStars component
  src/components/GitStars.tsx
  tsconfig.json
Labels: review needed :eyes:, internal :house:

#200 Add "edit page" button back to UseCases layout banner
  src/layouts/UseCases.tsx
Labels: review needed :eyes:

#202 Fix Nav dropdown menu positioning
  src/components/Nav/Dropdown.tsx
  src/components/Nav/Menu.tsx
Labels: review needed :eyes:

#187 Migrate /layer-2 page
  src/components/Layer2/Layer2Onboard.tsx
  src/components/Layer2ProductCard.tsx
  src/components/ProductList.tsx
  src/components/RollupProductDevDoc.tsx
  src/data/layer-2/layer-2.json
  src/data/layer-2/layer-2.ts
  src/intl/en/page-layer-2.json
  src/lib/utils/translations.ts
  src/pages/layer-2.tsx
Labels: review needed :eyes:, content :fountain_pen:, translation :earth_africa:

#193 feat: Translation program contributors page
  src/lib/utils/translations.ts
  src/pages/contributing/translation-program/contributors.tsx
Labels: review needed :eyes:, translation :earth_africa:

#201 Fix EthVideo component
  next.config.js
  package.json
  src/components/EthVideo.tsx
  yarn.lock
Labels: review needed :eyes:, internal :house:, dependencies :package:

#189 feat:`/contributing/translation-program/acknowledgements/` page
  src/components/Link.tsx
  src/components/TranslationLeaderboard.tsx
  src/lib/utils/translations.ts
  src/pages/contributing/translation-program/acknowledgements.tsx
  tsconfig.json
Labels: review needed :eyes:, internal :house:, translation :earth_africa:

#204 Fix Quiz styling
  src/components/Quiz/QuizWidget/QuizContent.tsx
  src/components/Quiz/QuizWidget/QuizRadioGroup.tsx
Labels: review needed :eyes:

#205 Update 7.24.4
  public/heroes/garden.jpg
  public/heroes/guides-hub-hero.jpg
  src/components/CommunityEvents/index.tsx
  src/intl/en/page-assets.json
  src/pages/assets.tsx
Labels: review needed :eyes:, content :fountain_pen:, translation :earth_africa:

#181 Add "What is Ethereum" page
  package.json
  src/components/AdoptionChart.tsx
  src/components/EnergyConsumptionChart.tsx
  src/lib/utils/translations.ts
  src/pages/what-is-ethereum.tsx
  yarn.lock
Labels: review needed :eyes:, content :fountain_pen:, dependencies :package:, translation :earth_africa:

#198 Fix translation banner logic for /contributing paths
  src/layouts/RootLayout.tsx
Labels: review needed :eyes:

#192 Add missing glossary namespace
  src/lib/utils/translations.ts
Labels: review needed :eyes:, translation :earth_africa:

#217 Fix: CTA label rendering inside ProductList component
  src/components/ProductList.tsx
  src/pages/dapps.tsx
  src/pages/layer-2.tsx
Labels: review needed :eyes:, content :fountain_pen:

#218 Home revalidate daily
  package.json
  src/pages/index.tsx
  yarn.lock
Labels: review needed :eyes:, content :fountain_pen:, dependencies :package:

#222 Fix last deploy date
  src/pages/quizzes.tsx
Labels: review needed :eyes:, content :fountain_pen:

#210 Update and enable Search component
  .env.example
  src/components/Search/index.tsx
  src/lib/utils/sanitizeHitTitle.ts
Labels: review needed :eyes:

#215 Fix i18n strings in SideNavMobile component
  src/components/SideNavMobile.tsx
Labels: review needed :eyes:

#191 PageHero & ActionCard image refactors
  src/components/ActionCard.tsx
  src/components/Hero/HomeHero/index.tsx
  src/components/PageHero.tsx
  src/pages/community.tsx
  src/pages/index.tsx
Labels: review needed :eyes:, content :fountain_pen:

#216 Fix focus state for auto-linked headings
  src/components/MdComponents.tsx
Labels: review needed :eyes:

#225 Remove react-i18next on tutorials page
  src/pages/developers/tutorials.tsx
Labels: review needed :eyes:

#226 Hot-fix import order
  src/pages/developers/tutorials.tsx
Labels: review needed :eyes:

#203 Html direction update on locale change
  src/hooks/useLocaleDirection.ts
  src/pages/_app.tsx
Labels: review needed :eyes:, content :fountain_pen:, tooling :wrench:

#211 Fix RTL logic for translation banners
  src/components/TranslationBanner.tsx
  src/components/TranslationBannerLegal.tsx
  src/layouts/RootLayout.tsx
Labels: review needed :eyes:

#221 Remaining small TODOs
  src/components/Codeblock.tsx
  src/components/ExpandableCard.tsx
  src/components/Staking/StakingProductsCardGrid.tsx
  src/components/UpcomingEventsList.tsx
Labels: review needed :eyes:

#213 SideNav / TableOfContents fixes
  src/components/SideNav.tsx
  src/components/TableOfContents/TableOfContentsMobile.tsx
  src/components/TableOfContents/index.tsx
  src/lib/utils/toc.ts
Labels: review needed :eyes:

#224 Add Guides hub hero
  src/layouts/Static.tsx
Labels: review needed :eyes:

#214 Fix PageMetadata/OG images
  src/components/PageMetadata.tsx
Labels: review needed :eyes:

#233 chore: remove unused ReleaseBanner component
  src/components/ReleaseBanner.tsx
  tsconfig.json
Labels: review needed :eyes:, internal :house:

#229 Fix roadmap hero to match production
  src/layouts/Roadmap.tsx
Labels: review needed :eyes:

#238 Netlify build function size
  netlify.toml
Labels: internal :house:

#230 Fix: load all contributors data
  src/components/Contributors.tsx
Labels: review needed :eyes:, tooling :wrench:, dependencies :package:

#219 feat: Stablecoins page
  src/components/CalloutBanner.tsx
  src/components/CardList.tsx
  src/components/DataProductCard.tsx
  src/components/StablecoinAccordion/AccordionCustomItem.tsx
  src/components/StablecoinAccordion/index.tsx
  src/components/StablecoinAccordion/useStablecoinAccordion.ts
  src/components/StablecoinAccordion/utils.ts
  src/components/StablecoinBoxGrid.tsx
  src/components/StablecoinsTable.tsx
  src/intl/am/page-stablecoins.json
  src/intl/ar/page-stablecoins.json
  src/intl/az/page-stablecoins.json
  src/intl/bg/page-stablecoins.json
  src/intl/bn/page-stablecoins.json
  src/intl/ca/page-stablecoins.json
  src/intl/cs/page-stablecoins.json
  src/intl/de/page-stablecoins.json
  src/intl/el/page-stablecoins.json
  src/intl/en/page-stablecoins.json
  src/intl/es/page-stablecoins.json
  src/intl/fa/page-stablecoins.json
  src/intl/fi/page-stablecoins.json
  src/intl/fil/page-stablecoins.json
  src/intl/fr/page-stablecoins.json
  src/intl/hi/page-stablecoins.json
  src/intl/hr/page-stablecoins.json
  src/intl/hu/page-stablecoins.json
  src/intl/hy-am/page-stablecoins.json
  src/intl/id/page-stablecoins.json
  src/intl/ig/page-stablecoins.json
  src/intl/it/page-stablecoins.json
  src/intl/ja/page-stablecoins.json
  src/intl/km/page-stablecoins.json
  src/intl/kn/page-stablecoins.json
  src/intl/ko/page-stablecoins.json
  src/intl/ml/page-stablecoins.json
  src/intl/mr/page-stablecoins.json
  src/intl/ms/page-stablecoins.json
  src/intl/nl/page-stablecoins.json
  src/intl/pcm/page-stablecoins.json
  src/intl/pl/page-stablecoins.json
  src/intl/pt-br/page-stablecoins.json
  src/intl/pt/page-stablecoins.json
  src/intl/ro/page-stablecoins.json
  src/intl/ru/page-stablecoins.json
  src/intl/se/page-stablecoins.json
  src/intl/sl/page-stablecoins.json
  src/intl/sr/page-stablecoins.json
  src/intl/sw/page-stablecoins.json
  src/intl/tr/page-stablecoins.json
  src/intl/uk/page-stablecoins.json
  src/intl/vi/page-stablecoins.json
  src/intl/zh-tw/page-stablecoins.json
  src/intl/zh/page-stablecoins.json
  src/lib/api/stablecoinsData.ts
  src/lib/constants.ts
  src/lib/utils/translations.ts
  src/pages/stablecoins.tsx
  tsconfig.json
Labels: review needed :eyes:, internal :house:, content :fountain_pen:, tooling :wrench:, translation :earth_africa:

#207 Implement StatsBoxGrid using getStaticProps with caching
  src/components/Staking/StakingStatsBox.tsx
  src/components/StatErrorMessage.tsx
  src/components/StatLoadingMessage.tsx
  src/components/StatsBoxGrid/GridItem.tsx
  src/components/StatsBoxGrid/RangeSelector.tsx
  src/components/StatsBoxGrid/index.tsx
  src/components/StatsBoxGrid/useStatsBoxGrid.tsx
  src/lib/api/fetchNodes.ts
  src/lib/api/fetchTotalEthStaked.ts
  src/lib/api/fetchTotalValueLocked.ts
  src/lib/api/fetchTxCount.ts
  src/lib/constants.ts
  src/lib/types.ts
  src/lib/utils/weiToRoundedEther.ts
  src/pages/index.tsx
  src/pages/staking/index.tsx
  src/pages/what-is-ethereum.tsx
  tsconfig.json
Labels: review needed :eyes:, internal :house:, content :fountain_pen:, tooling :wrench:

#235 Enable What is Ethereum stats
  src/pages/what-is-ethereum.tsx
Labels: review needed :eyes:, internal :house:, content :fountain_pen:, tooling :wrench:

#199 Translation banner logic for non-markdown pages
  src/layouts/RootLayout.tsx
  src/lib/interfaces.ts
  src/lib/types.ts
  src/lib/utils/existsNamespace.ts
  src/lib/utils/translations.ts
  src/pages/404.tsx
  src/pages/[...slug].tsx
  src/pages/assets.tsx
  src/pages/bug-bounty.tsx
  src/pages/community.tsx
  src/pages/contributing/translation-program/acknowledgements.tsx
  src/pages/contributing/translation-program/contributors.tsx
  src/pages/dapps.tsx
  src/pages/developers/index.tsx
  src/pages/developers/learning-tools.tsx
  src/pages/developers/local-environment.tsx
  src/pages/developers/tutorials.tsx
  src/pages/eth.tsx
  src/pages/gas.tsx
  src/pages/get-eth.tsx
  src/pages/index.tsx
  src/pages/languages.tsx
  src/pages/layer-2.tsx
  src/pages/learn.tsx
  src/pages/quizzes.tsx
  src/pages/roadmap/vision.tsx
  src/pages/run-a-node.tsx
  src/pages/stablecoins.tsx
  src/pages/staking/deposit-contract.tsx
  src/pages/staking/index.tsx
  src/pages/wallets/find-wallet.tsx
  src/pages/wallets/index.tsx
  src/pages/what-is-ethereum.tsx
Labels: review needed :eyes:, content :fountain_pen:, tooling :wrench:, translation :earth_africa:

#239 Fix data fetching errors
  .env.example
  next.config.js
  src/lib/api/calendarEvents.ts
  src/lib/api/fetchNodes.ts
  src/lib/api/fetchTotalEthStaked.ts
  src/lib/api/fetchTotalValueLocked.ts
  src/lib/api/fetchTxCount.ts
  src/lib/api/ghRepoData.ts
  src/lib/api/stablecoinsData.ts
Labels: review needed :eyes:, internal :house:

#240 Redirect /en to /
  public/_redirects
Labels: review needed :eyes:

#227 Update components list in tsconfig
  src/components/BaseStories/Heading.stories.tsx
  src/components/BaseStories/Text.stories.tsx
  src/components/BugBountyPoints.tsx
  src/components/ImageCard.tsx
  src/components/Layout.tsx
  src/pages/bug-bounty.tsx
  tsconfig.json
Labels: review needed :eyes:, internal :house:, content :fountain_pen:

#241 Matomo setup
  .env.example
  package.json
  src/lib/utils/matomo.ts
  src/pages/_app.tsx
  yarn.lock
Labels: review needed :eyes:, content :fountain_pen:, dependencies :package:

#243 Remove axios calls
  src/lib/api/ghRepoData.ts
  src/scripts/crowdin/reports/reportsHelpers.ts
Labels: review needed :eyes:

#242 cleanup: remove gatsby references
  src/components/PageHero.tsx
  src/components/SideNav.tsx
  src/global.d.ts
  src/layouts/Roadmap.tsx
  src/lib/utils/url.ts
  src/pages/bug-bounty.tsx
Labels: review needed :eyes:, content :fountain_pen:

#248 Filter cancelled events
  src/lib/api/calendarEvents.ts
Labels: review needed :eyes:

#244 HubHero layout shifting
  src/components/Hero/HubHero/index.tsx
Labels: review needed :eyes:

#245 DocsNav bug
  src/data/developer-docs-links.yaml
Labels: review needed :eyes:

#246 Fix md image dimensions
  src/components/MarkdownImage.tsx
Labels: review needed :eyes:

#247 fix: translated images link
  src/components/MarkdownImage.tsx
Labels: review needed :eyes:

#249 Events order and fetching fix
  src/lib/api/calendarEvents.ts
Labels: review needed :eyes:

#156 Fix Algolia crawler DOM dependencies
  src/components/MainArticle.tsx
  src/components/MdComponents.tsx
  src/layouts/Docs.tsx
  src/layouts/Roadmap.tsx
  src/layouts/Staking.tsx
  src/layouts/Static.tsx
  src/layouts/Tutorial.tsx
  src/layouts/Upgrade.tsx
  src/layouts/UseCases.tsx
  src/lib/constants.ts
  src/lib/utils/url.ts
  src/pages/404.tsx
  src/pages/assets.tsx
  src/pages/bug-bounty.tsx
  src/pages/community.tsx
  src/pages/contributing/translation-program/acknowledgements.tsx
  src/pages/contributing/translation-program/contributors.tsx
  src/pages/dapps.tsx
  src/pages/developers/index.tsx
  src/pages/developers/learning-tools.tsx
  src/pages/developers/local-environment.tsx
  src/pages/developers/tutorials.tsx
  src/pages/eth.tsx
  src/pages/gas.tsx
  src/pages/get-eth.tsx
  src/pages/index.tsx
  src/pages/languages.tsx
  src/pages/layer-2.tsx
  src/pages/learn.tsx
  src/pages/quizzes.tsx
  src/pages/roadmap/vision.tsx
  src/pages/run-a-node.tsx
  src/pages/stablecoins.tsx
  src/pages/staking/deposit-contract.tsx
  src/pages/staking/index.tsx
  src/pages/wallets/find-wallet.tsx
  src/pages/wallets/index.tsx
  src/pages/what-is-ethereum.tsx
Labels: review needed :eyes:, internal :house:, content :fountain_pen:, tooling :wrench:

#253 cleanup: remove empty wrapper
  src/pages/developers/tutorials.tsx
Labels: review needed :eyes:

#255 Refactor/stories
  .storybook/main.ts
  package.json
  src/components/BannerNotification/BannerNotification.stories.tsx
  src/components/BaseStories/Heading.stories.tsx
  src/components/BaseStories/Text.stories.tsx
  src/components/Hero/HubHero/HubHero.stories.tsx
  yarn.lock
Labels: review needed :eyes:, dependencies :package:

#256 chore: restore chromatic GH runner
  .github/workflows/chromatic.yml
Labels: tooling :wrench:
