Repository ethereum/ethereum-org-fork, pull requests merged in 2023-09, with the labels that each got.

#18 Downgrade mdx to v1
  package.json
  src/components/History/NetworkUpgradeSummary.tsx
  yarn.lock
Labels: review needed :eyes:, dependencies :package:

#19 MD tables
  src/components/MarkdownTable.tsx
  src/layouts/Static.tsx
Labels: review needed :eyes:

#20 feat: Breadcrumbs & get last update date
  .env.example
  i18n.config.json
  package.json
  src/components/Breadcrumbs/index.tsx
  src/layouts/Static.tsx
  src/lib/constants.ts
  src/lib/types.ts
  src/lib/utils/gh.ts
  src/lib/utils/md.ts
  src/lib/utils/time.ts
  src/lib/utils/translations.ts
  src/pages/[...slug].tsx
  yarn.lock
Labels: review needed :eyes:, content :fountain_pen:, dependencies :package:

#21 Fix `DocLink` styles
  src/components/DocLink.tsx
Labels: review needed :eyes:

#22 Update 7.20.0
  .all-contributorsrc
  README.md
  package.json
  public/content/developers/docs/apis/json-rpc/index.md
  public/content/developers/docs/nodes-and-clients/index.md
  public/content/glossary/index.md
  public/dapps/ankr.png
  public/dapps/api3.png
  public/dapps/arweave.png
  public/dapps/cyberconnect.png
  public/dapps/gm.png
  public/dapps/graph.png
  public/dapps/ipfs.png
  public/dapps/kyberswap.png
  public/dapps/lido.png
  public/dapps/mirror.png
  public/dapps/multichain.png
  public/dapps/osuvox.png
  public/dapps/rubic.png
  public/dapps/skiff.png
  public/dapps/spatial.png
  public/dapps/spruce.png
  public/dapps/status.png
  public/dapps/xmtp.png
  src/components/Footer.tsx
  src/components/Glossary/GlossaryDefinition/GlossaryDefinition.stories.tsx
  src/components/Glossary/GlossaryDefinition/index.tsx
  src/components/Glossary/GlossaryTooltip/GlossaryTooltip.stories.tsx
  src/components/Glossary/GlossaryTooltip/index.tsx
  src/components/HorizontalCard.tsx
  src/components/MdLink.tsx
  src/components/Nav/useNav.ts
  src/components/Tooltip.tsx
  src/components/icons/Icons.stories.tsx
  src/intl/en/glossary.json
  src/intl/en/page-dapps.json
  tsconfig.json
  yarn.lock
Labels: review needed :eyes:, documentation :book:, internal :house:, content :fountain_pen:, dependencies :package:

#23 Update v7.20.1
  .all-contributorsrc
  README.md
  docs/ds-implementation.md
  public/content/community/code-of-conduct/index.md
  public/content/community/get-involved/index.md
  public/content/developers/docs/apis/json-rpc/index.md
  public/content/developers/docs/bridges/index.md
  public/content/developers/docs/design-and-ux/index.md
  public/content/developers/docs/ides/index.md
  public/content/developers/docs/networks/index.md
  public/content/energy-consumption/index.md
  public/content/guides/how-to-use-a-wallet/index.md
  public/content/roadmap/account-abstraction/index.md
  public/content/roadmap/index.md
  public/content/roadmap/statelessness/index.md
  public/content/security/index.md
  public/content/translations/it/roadmap/statelessness/index.md
  public/content/translations/zh/developers/docs/oracles/index.md
  src/data/community-events.json
  src/intl/en/page-wallets.json
Labels: review needed :eyes:, documentation :book:, internal :house:, event :date:

#29 Next/Chakra image integration
  src/components/Image.tsx
  src/components/MarkdownImage.tsx
Labels: review needed :eyes:

#28 Add template logic to [...slug]
  src/pages/[...slug].tsx
Labels: review needed :eyes:, content :fountain_pen:

#24 Next link integration
  src/components/ButtonLink.tsx
  src/components/ButtonTwoLines/index.tsx
  src/components/Link.tsx
  src/components/Nav/Dropdown.tsx
  src/components/StablecoinBoxGrid.tsx
Labels: review needed :eyes:, content :fountain_pen:

#32 Update layout import architecture
  src/layouts/Docs.tsx
  src/layouts/Event.tsx
  src/layouts/Roadmap.tsx
  src/layouts/Staking.tsx
  src/layouts/Upgrade.tsx
  src/layouts/UseCases.tsx
  src/layouts/index.ts
  src/pages/[...slug].tsx
Labels: review needed :eyes:, content :fountain_pen:

#26 Link - active styles
  src/components/Link.tsx
  src/lib/utils/url.ts
Labels: review needed :eyes:

#34 Fix css property casing
  src/@chakra-ui/styles.ts
Labels: review needed :eyes:
