Repository ethereum/ethereum-org-fork, pull requests merged in 2024-01, with the labels that each got.

#261 Fix image device size cap at 1504px
  next.config.js
Labels: internal :house:

#260 Fix display logic for hero elements on UseCases layout
  src/layouts/UseCases.tsx
Labels: review needed :eyes:

#263 SkipLink component
  src/components/Link.tsx
  src/components/MainArticle.tsx
  src/components/SkipLink.tsx
  src/layouts/RootLayout.tsx
  src/lib/utils/url.ts
Labels: review needed :eyes:

#270 Redirect `/en/stablecoins` to `/stablecoins`
  public/_redirects
Labels: review needed :eyes:

#271 Fix: Use absolute path to check if intl namespace exists
  src/lib/constants.ts
  src/lib/utils/existsNamespace.ts
  src/lib/utils/translations.ts
  src/pages/404.tsx
  src/pages/developers/learning-tools.tsx
  src/pages/developers/local-environment.tsx
  src/pages/developers/tutorials.tsx
  src/pages/layer-2.tsx
  src/pages/staking/deposit-contract.tsx
  src/pages/wallets/find-wallet.tsx
  src/pages/wallets/index.tsx
Labels: review needed :eyes:, content :fountain_pen:, tooling :wrench:, translation :earth_africa:

#268 Fix: direction-responsive margins and padding
  public/content/translations/ja/developers/docs/nodes-and-clients/client-diversity/index.md
  public/content/translations/ja/history/index.md
  public/content/translations/tr/history/index.md
  public/content/translations/zh/developers/docs/nodes-and-clients/client-diversity/index.md
  src/pages/community.tsx
  src/pages/contributing/translation-program/acknowledgements.tsx
  src/pages/dapps.tsx
  src/pages/developers/index.tsx
  src/pages/developers/local-environment.tsx
  src/pages/developers/tutorials.tsx
  src/pages/eth.tsx
  src/pages/gas.tsx
  src/pages/index.tsx
  src/pages/languages.tsx
  src/pages/stablecoins.tsx
  src/pages/staking/deposit-contract.tsx
  src/pages/wallets/index.tsx
Labels: review needed :eyes:, content :fountain_pen:

#272 adjust roadmap header image height to match production
  src/layouts/Roadmap.tsx
Labels: review needed :eyes:
